version: '2'
services:
  proxy:
    build: ./Proxy
    ports:
     - "8081:8081"
    volumes:
     - .:/usr/src/proxy
    depends_on:
     - redis
    links:
     - app
  app:
    build: ./App
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
  redis:
    image: redis
