---
# tasks file for proxy
- name: Cloning Simple Set Repository
  git: repo=https://github.com/rahuja910/ProxyServer.git dest=/src/ProxyServer/
  sudo: yes   

- name: npm install
  npm: path=/src/ProxyServer/
  sudo: yes

- name: start the proxy ProxyServer
  command: forever start /src/ProxyServer/proxy.js